#!/usr/bin/ruby

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))

require 'rubygems'
require 'bundler/setup'
Bundler.require
require 'mock_rails'
require 'blueprint'
require 'irb'

AridCache.framework.init
Blueprint.seeds

require 'will_paginate/version'
if WillPaginate::VERSION::MAJOR < 3
  WillPaginate.enable_activerecord
else
  require 'will_paginate/collection'
  require 'will_paginate/finders/active_record'
  WillPaginate::Finders::ActiveRecord.enable!
end

ARGV.clear
IRB.start